import { db } from './db.js'
import {
  collection,
  addDoc,
  query
} from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js'

const abastecer2023 = [
  {
    empreendimento: 'CONDOMÍNIO VOG',
    tipo: 'EMISSÃO',
    empresa: 'DENICRED CONSTRUTORA E INCORPORADORA',
    nomeInteressado: 'DENICRED CONSTRUTORA E INCORPORADORA',
    telefone: 7332880542,
    celular: '',
    email: 'ADM@BETA7ENG.COM.BR',
    vt: '124VT-23IS',
    data_vt: '05/23/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '36927/22',
    data: '2023'
  },
  {
    empreendimento: 'ATAKADÃO ATAKAREJO',
    tipo: 'RENOVAÇÃO',
    empresa: 'ATAKAREJO DISTRIBUIDOR DE ALIMENTOS E BEBIDAS S/A',
    nomeInteressado: 'LUIZ PAULO OLIVEIRA',
    telefone: 7134608794,
    celular: 71991297418,
    email: 'LUIZ.OLIVEIRA@DAMRAK.COM.BR',
    vt: '047VT/23-IS',
    data_vt: '03/06/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: 'PROC 4535/2022',
    data: '2023'
  },
  {
    empreendimento: 'MINEIRÃO ATACAREJO',
    tipo: 'RENOVAÇÃO',
    empresa: 'DMA DISTRIBUIDORA S/A',
    nomeInteressado: 'ROBLES BARBOSA',
    telefone: 3133895548,
    celular: 31997132641,
    email: 'ROBLES.BARBOSA@GRUPODMA.COM.BR',
    vt: '102VT/23-IS',
    data_vt: '05/10/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '3403/23',
    data: '2023'
  },
  {
    empreendimento: 'CONDOMÍNIO CAPITANIA RESIDENCE',
    tipo: 'EMISSÃO',
    empresa: '',
    nomeInteressado: 'ANDERSON MOURA DE NOVAIS',
    telefone: '',
    celular: '',
    email: 'magnaconstrutora@outlook.com',
    vt: '127VT/23-IS',
    data_vt: '05/30/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '3553/23',
    data: '2023'
  },
  {
    empreendimento: 'ESCOLA MODELO EM TEMPO INTEGRAL (MEDEIROS NETO)',
    tipo: 'EMISSÃO',
    empresa: 'QUALY ENGENHARIA LTDA',
    nomeInteressado: 'BIANCA COSTA BRITO',
    telefone: 7133427602,
    celular: '',
    email: 'BIANCA.QUALY@OUTLOOK.COM',
    vt: '079VT/23-IS',
    data_vt: '04/27/2023',
    localidade: 'MEDEIROS NETO',
    status: 'ARQUIVADA',
    protocolo: 'PROC 826/23',
    data: '2023'
  },
  {
    empreendimento: 'RESIDENCIAL DO MATO',
    tipo: 'EMISSÃO',
    empresa: 'ROSANITA CONSTRUÇÕES DE IMÓVEIS',
    nomeInteressado: 'ONILSON PALMITO DE ALMEIDA',
    telefone: '',
    celular: 73988000086,
    email: 'ONILSONPALMITO@HOTMAIL.COM',
    vt: '157VT/23-IS',
    data_vt: '06/27/2023',
    localidade: "ARRAIAL D'AJUDA",
    status: 'ARQUIVADA',
    protocolo: '38987/22',
    data: '2023'
  },
  {
    empreendimento: 'SOMA BARTHOLO',
    tipo: 'EMISSÃO',
    empresa: 'SOMA ITACIMIRIM SPE - EMPREENDIMENTOS IMOBILIÁRIOS S/A',
    nomeInteressado: 'GILBERT CANAL',
    telefone: 2737674047,
    celular: 27999052008,
    email: 'marcelo.castelan@somaurbanismo.com.br',
    vt: '074VT/23-IS',
    data_vt: '05/19/2023',
    localidade: 'TRANCOSO',
    status: 'ARQUIVADA',
    protocolo: '4018/23',
    data: '2023'
  },
  {
    empreendimento: 'TERRAMATER II',
    tipo: 'EMISSÃO',
    empresa: 'LCM CONSTRUÇÃO E COMÉRCIO S/A',
    nomeInteressado: 'HÉLIO VALENTE LIPIANI',
    telefone: 3132987050,
    celular: 31999770711,
    email: 'heliolipiani@lcmcontrucao.com.br',
    vt: '198/VT-IS',
    data_vt: '06/18/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '2490/23',
    data: '2023'
  },
  {
    empreendimento: 'HORIZONTE AZUL',
    tipo: 'EMISSÃO',
    empresa: 'NS COSTA CONSTRUTORA - ME',
    nomeInteressado: 'NS COSTA CONSTRUTORA - ME',
    telefone: '',
    celular: 73991910671,
    email: '',
    vt: '123VT/23-IS',
    data_vt: '',
    localidade: 'SANTA CRUZ CABRÁLIA',
    status: 'ARQUIVADA',
    protocolo: '7064/23',
    data: '2023'
  },
  {
    empreendimento: 'VERBENA INFINITY',
    tipo: 'EMISSÃO',
    empresa: 'INFINITY VERBENA EMPREENDIMENTOS IMOBILIÁRIOS SEP LTDA',
    nomeInteressado: 'JORGE GUERRIERI',
    telefone: '',
    celular: 73991014710,
    email: 'jorgeguerrieri.engcivil@gmail.com',
    vt: '150VT/23-IS',
    data_vt: '06/21/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '7944/23',
    data: '2023'
  },
  {
    empreendimento: 'RESIDENCIAL ANTONIETA',
    tipo: 'EMISSÃO',
    empresa: 'ARARAI25 SPE LTDA',
    nomeInteressado: 'ARARAI25 SPE LTDA',
    telefone: '',
    celular: 61981370272,
    email: 'ATENDIMENTO@OVNCONSULTORIA.COM',
    vt: '161VT/23-IS',
    data_vt: '07/03/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '8038/23',
    data: '2023'
  },
  {
    empreendimento: 'SQUADRO EMPREENDIMENTOS',
    tipo: 'RENOVAÇÃO',
    empresa: 'SQUADRO EMPREENDIMENTOS IMOBILIÁRIOS LTDA',
    nomeInteressado: 'ONILSON PALMITO DE ALMEIDA',
    telefone: 7398800086,
    celular: '',
    email: 'ONILSONPALMITO@HOTMAIL.COM',
    vt: '202/VT/23-IS',
    data_vt: '07/20/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '10363/23',
    data: '2023'
  },
  {
    empreendimento: 'COLINA PARK',
    tipo: 'EMISSÃO',
    empresa: 'CASA & TERRA IMOBILIÁRIA E ENGENARIA LTDA',
    nomeInteressado: 'CASA & TERRA EMPREENDIMENTOS',
    telefone: 6132215735,
    celular: '',
    email: 'PROJETOS.ENG@CASAETERRA.COM',
    vt: '193VT/23-IS',
    data_vt: '06/14/2023',
    localidade: 'EUNÁPOLIS',
    status: 'ARQUIVADA',
    protocolo: '10267/23',
    data: '2023'
  },
  {
    empreendimento: 'TESLA EMPREENDIMENTOS',
    tipo: 'RENOVAÇÃO',
    empresa: 'TESLA EMPREENDIMENTOS IMOBILIÁRIOS',
    nomeInteressado: 'ONILSON PALMITO DE ALMEIDA',
    telefone: '',
    celular: 73988000086,
    email: 'ONILSONPALMITO@HOTMAIL.COM',
    vt: '195VT/23-IS',
    data_vt: '06/14/2023',
    localidade: 'SANTA CRUZ CABRÁLIA',
    status: 'ARQUIVADA',
    protocolo: '10360/23',
    data: '2023'
  },
  {
    empreendimento: 'HOTEL PRÍNCIPE DO MUTA',
    tipo: 'RENOVAÇÃO',
    empresa: 'MUTARI EMPREENDIMENTOS IMOBILIÁRIOS',
    nomeInteressado: 'PAULO JORGE PICCOLI',
    telefone: '',
    celular: 73988000086,
    email: 'ONILSONPALMITO@HOTMAIL.COM',
    vt: '194VT/23-IS',
    data_vt: '06/14/2023',
    localidade: 'SANTA CRUZ CABRÁLIA',
    status: 'ARQUIVADA',
    protocolo: '10356/23',
    data: '2023'
  },
  {
    empreendimento: 'LOTEAMENTO GRANVILLE',
    tipo: 'RETIFICAÇÃO',
    empresa: 'SMR SANTANA INCORPORADORA LTDA',
    nomeInteressado: 'ROGERIO PEREIRA SANTANA',
    telefone: '',
    celular: 73999866561,
    email: 'rsprojetos@hotmail.com',
    vt: '',
    data_vt: '09/22/2023',
    localidade: 'ITABATÃ',
    status: 'ARQUIVADA',
    protocolo: '13359/23',
    data: '2023'
  },
  {
    empreendimento: 'GOLDEN PARK',
    tipo: 'RENOVAÇÃO',
    empresa: 'DACASA INCORPORAÇÃO IMOBILIÁRIA',
    nomeInteressado: 'LUCAS COSTA GUIMARÃES',
    telefone: '',
    celular: 73999926049,
    email: 'engenharia2.eldorado@hotmail.com',
    vt: '214VT/23-IS',
    data_vt: '08/07/2023',
    localidade: 'TEIXEIRA DE FREITAS',
    status: 'ARQUIVADA',
    protocolo: '12198/23',
    data: '2023'
  },
  {
    empreendimento: 'NOVA MORADA',
    tipo: 'EMISSÃO',
    empresa: 'GALEYA EMPREENDIMENTOS IMOBILIÁRIOS LTDA',
    nomeInteressado: 'LINDOMAR ALVES DE BRITO',
    telefone: '',
    celular: 73988325066,
    email: 'INTEGRARADM01@GMAIL.COM',
    vt: '228VT/22-IS',
    data_vt: '09/01/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '12803/23',
    data: '2023'
  },
  {
    empreendimento: 'RECANTO DAS ÁGUAS II',
    tipo: 'EMISSÃO',
    empresa: 'LFJ URBANISMO LTDA',
    nomeInteressado: 'JAIRO BARBOSA DE OLIVEIRA',
    telefone: '',
    celular: 73999622031,
    email: 'fabriciobarbosa.engcivil@gmail.com',
    vt: '237VT/23-IS',
    data_vt: '09/14/2023',
    localidade: 'TEIXEIRA DE FREITAS',
    status: 'ARQUIVADA',
    protocolo: '13388/23',
    data: '2023'
  },
  {
    empreendimento: 'CIDADEL BAIRRO PLANEJADO',
    tipo: 'EMISSÃO',
    empresa: 'IMOBILIÁRIA SÃO FRANCISCO SPE LTDA',
    nomeInteressado: 'RODRIGO CORTES',
    telefone: '',
    celular: '(73)99925-7874',
    email: 'RODRIGO@ISH.COM.BR',
    vt: '226VT/23-IS',
    data_vt: '08/30/2023',
    localidade: 'TEIXEIRA DE FREITAS',
    status: 'ENC. AO EL',
    protocolo: '14247/23',
    data: '2023'
  },
  {
    empreendimento: 'PORTO ROYAL VILLE',
    tipo: 'EMISSÃO',
    empresa: 'PORTO ROYAL INCORPORADORA LTDA',
    nomeInteressado: 'GILVAN JEZLER',
    telefone: 7330866291,
    celular: 73981532080,
    email: 'MORENACOLARES@FOLIUS.COM.BR',
    vt: '249VT/23-IS',
    data_vt: '10/04/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '15268/23',
    data: '2023'
  },
  {
    empreendimento: 'BROMÉLIA RESIDENCE',
    tipo: 'EMISSÃO',
    empresa: 'SAINT LAZARO EMPREENDIMENTOS',
    nomeInteressado: 'SAINT LAZARO',
    telefone: 7336791227,
    celular: 73999291379,
    email: 'CONSTRUTORASAINTLAZARO@GMAIL.COM',
    vt: '255VT/23-IS',
    data_vt: '10/17/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '15925/23',
    data: '2023'
  },
  {
    empreendimento: 'LOTEAMENTO RESIDENCIAL PALMIRA',
    tipo: 'EMISSÃO',
    empresa: 'CARLOS ARAUJO LAPA',
    nomeInteressado: 'CARLOS ANTONIO ALVES PEREIRA JUNIOR',
    telefone: '',
    celular: 73981592495,
    email: 'CARLOS@GISMATEC.COM.BR',
    vt: '247VT/23-IS',
    data_vt: '10/03/2023',
    localidade: 'EUNÁPOLIS',
    status: 'ARQUIVADA',
    protocolo: '15772/23',
    data: '2023'
  },
  {
    empreendimento: 'BRISAS DO MUTARI',
    tipo: 'EMISSÃO',
    empresa: 'BRISAS DO MUTARI EMPREENDIMENTOS',
    nomeInteressado: 'EDUARDO BENTO',
    telefone: '',
    celular: 14998505087,
    email: 'EDUARDOBENTO@HOTMAIL.COM',
    vt: '253VT/23-IS',
    data_vt: '10/17/2023',
    localidade: 'SANTA CRUZ CABRALIA',
    status: 'ARQUIVADA',
    protocolo: '13422/23',
    data: '2023'
  },
  {
    empreendimento: 'CONDOMINIO VISTA MUNDAÍ',
    tipo: 'EMISSÃO',
    empresa: 'LENADRO GARCIA DE MATTOS',
    nomeInteressado: 'LEANDRO GARCIA DE MATTOS',
    telefone: '',
    celular: 73988024766,
    email: 'LG.MATTOS@UOL.COM.BR',
    vt: '257VT/23-IS',
    data_vt: '',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '16237/23',
    data: '2023'
  },
  {
    empreendimento: 'CONDOMINIO TRIÂNGULO',
    tipo: 'EMISSÃO',
    empresa: 'KLAM CONSTRUÇÕES E EDIFICAÇÕES',
    nomeInteressado: 'ONILSON PALMITO DE ALMEIDA',
    telefone: '',
    celular: 73988000086,
    email: 'ONILSONPALMITO@HOTMAIL.COM',
    vt: '292VT/23-IS',
    data_vt: '12/12/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '16234/23',
    data: '2023'
  },
  {
    empreendimento: 'KUARA EMPREENDIMENTOS',
    tipo: 'EMISSÃO',
    empresa: '',
    nomeInteressado: 'ONILSON PALMITO DE ALMEIDA',
    telefone: '',
    celular: 73988000086,
    email: 'ONILSONPALMITO@HOTMAIL.COM',
    vt: '274VT/23-IS',
    data_vt: '10/20/2023',
    localidade: "ARRAIAL D'AJUDA",
    status: 'ARQUIVADA',
    protocolo: '16230/23',
    data: '2023'
  },
  {
    empreendimento: 'PORTAL CANOÊ',
    tipo: 'EMISSÃO',
    empresa: 'VF ENGENHARIA LTDA',
    nomeInteressado: 'LUCAS RODRIGUES VINHAS',
    telefone: '',
    celular: 73981532080,
    email: 'MORENACOLARES@FOLIUS.COM.BR',
    vt: '287VT/23-IS',
    data_vt: '11/16/2023',
    localidade: "ARRAIAL D'AJUDA",
    status: 'ARQUIVADA',
    protocolo: '1863/23',
    data: '2023'
  },
  {
    empreendimento: 'CASA JARDIM',
    tipo: 'EMISSÃO',
    empresa: 'VF ENGENHARIA LTDA',
    nomeInteressado: 'FRANCISCO VINHAS',
    telefone: '733086-6291',
    celular: 73981532080,
    email: 'MORENACOLARES@FOLIUS.COM.BR',
    vt: '017/VT/24-IS',
    data_vt: '01/17/2024',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '17638/23',
    data: '2023'
  },
  {
    empreendimento: 'RESIDENCIAL OUTEIRO DE TAPERAPUAN',
    tipo: 'RENOVAÇÃO',
    empresa: 'HABITA CONSULTORIA',
    nomeInteressado: 'ANDRE LUIZ DOS SANTOS',
    telefone: '',
    celular: '7399153-2743',
    email: 'GEISIANEARRUDA@HABITARPARTICIPAÇÕES.COM.BR',
    vt: '258VT/23-IS',
    data_vt: '10/19/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '16894/23',
    data: '2023'
  },
  {
    empreendimento: 'LOTEAMENTO VILA JARDIM',
    tipo: 'EMISSÃO',
    empresa: 'VILA JARDIM EMPREENDIMENTOS',
    nomeInteressado: 'ANDRE LUIZ DOS SANTOS',
    telefone: 16991532743,
    celular: 73999550620,
    email: 'GEIZIANEARRUDA@HABITAPARTICIPACOES.COM.BR',
    vt: '073VT/24-IS',
    data_vt: '03/05/2024',
    localidade: 'PORTO SEGURO',
    status: 'ENC. AO EL',
    protocolo: '17170/23',
    data: '2023'
  },
  {
    empreendimento: 'JOÃO DE TIBA',
    tipo: 'EMISSÃO',
    empresa: '',
    nomeInteressado: 'FERNANDA LOPES GUERRA',
    telefone: '',
    celular: 73999087778,
    email: 'FRENANDADAGUERRA.ADV@GMAIL.COM',
    vt: '272VT/23-IS',
    data_vt: '11/13/2023',
    localidade: 'SANTA CRUZ CABRALIA',
    status: 'ARQUIVADA',
    protocolo: '17174/23',
    data: '2023'
  },
  {
    empreendimento: 'RESIDENCIAL DIETER MORAES ',
    tipo: 'EMISSÃO',
    empresa: 'DIETER E MORAES EMPREENDIMENTOS',
    nomeInteressado: 'ONILSON PALMITO SW ALMEIDA',
    telefone: '',
    celular: 73988000086,
    email: 'ONILSONPALMITO@HOTMAIL.COM',
    vt: '256VT/23-IS',
    data_vt: '10/17/2023',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '16227/23',
    data: '2023'
  },
  {
    empreendimento: 'RESIDENCIAL POR DO SOL',
    tipo: 'EMISSÃO',
    empresa: 'CONSTRUTORA LGE LTDA',
    nomeInteressado: 'RENTO LEMES/SERGIO ANDRADE',
    telefone: '',
    celular: 73982462222,
    email: 'SERGIOANDRADE.ARQ@GMAIL.COM',
    vt: '074VT/24-IS',
    data_vt: '03/06/2024',
    localidade: 'TEIXEIRA DE FREITAS',
    status: 'ENC. AO EL',
    protocolo: '19131/23',
    data: '2023'
  },
  {
    empreendimento: 'CONCESSIONARIA TOPVEL CHEVROLET',
    tipo: 'EMISSÃO',
    empresa: '',
    nomeInteressado: 'TISSIANE CORREIA BORGES',
    telefone: '',
    celular: 71992649991,
    email: 'TISSIANEBORGES@MHRENGENHARIA.COM.BR',
    vt: '284VT/23-IS',
    data_vt: '11/09/2023',
    localidade: 'EUNÁPOLIS',
    status: 'ARQUIVADA',
    protocolo: '2294/23',
    data: '2023'
  },
  {
    empreendimento: 'MINEIRÃO ATACADISTA ',
    tipo: 'EMISSÃO',
    empresa: 'BRA PARTICIPAÇÕES EMPREENDIMENTOS',
    nomeInteressado: 'TISSIANE CORREIA BORGES',
    telefone: '',
    celular: 71992649991,
    email: 'TISSIANEBORGES@MHRENGENHARIA.COM.BR',
    vt: '298VT/23-IS',
    data_vt: '12/15/2023',
    localidade: 'ITAMARAJU',
    status: 'ARQUIVADA',
    protocolo: '2434/23',
    data: '2023'
  },
  {
    empreendimento: 'RESIDENCIAL RECANTO DAS FALÉSIAS',
    tipo: 'RENOVAÇÃO',
    empresa: 'SOUZA E FAGUNDES',
    nomeInteressado: 'ANNE FAGUNDES ',
    telefone: '',
    celular: 73988693533,
    email: 'SFAGUNDESCONSTRUTORAS@GMAIL.COM',
    vt: '21VT/24-IS',
    data_vt: '01/23/2024',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '21901/23',
    data: '2023'
  },
  {
    empreendimento: 'CONDOMINIO BRASIL IMPERIAL',
    tipo: 'RENOVAÇÃO',
    empresa: 'BRASIL IMPERIAL PRAIA RESORT EMPREENDIMENTOS',
    nomeInteressado: '',
    telefone: '',
    celular: 73998031553,
    email: 'MATHEUS@IMPERIALEMG.BA.COM',
    vt: '030VT/24-IS',
    data_vt: '01/25/2024',
    localidade: 'SANTA CRUZ CABRALIA',
    status: 'ENC. AO EL',
    protocolo: '23149/23',
    data: '2023'
  },
  {
    empreendimento: 'LOTEAMENTO PLANALTO VERDE',
    tipo: 'EMISSÃO',
    empresa: 'PLANALTO VERDE EMPREENDIMENTOS',
    nomeInteressado: '',
    telefone: '',
    celular: 73999919238,
    email: 'FAZINHO45679@HOTMAIL.COM',
    vt: '026VT/24-IS',
    data_vt: '01/24/2024',
    localidade: 'ITABATÃ',
    status: 'ARQUIVADA',
    protocolo: '23272/23',
    data: '2023'
  },
  {
    empreendimento: 'RESIDENCIAL VALE DO QUADRADO',
    tipo: 'RENOVAÇÃO',
    empresa: 'BRASIS FUNDO INVESTIMENTO',
    nomeInteressado: 'ANDRE RIBEIRO',
    telefone: '',
    celular: 71988101314,
    email: '',
    vt: '065VT/24-IS',
    data_vt: '02/25/2024',
    localidade: 'TRANCOSO',
    status: 'ARQUIVADA',
    protocolo: '2599/23',
    data: '2023'
  },
  {
    empreendimento: 'RESIDENCIAL VILA DOS VENTOS',
    tipo: 'EMISSÃO',
    empresa: 'JOSE AMARO MAGALHÃES',
    nomeInteressado: 'JOSE AMARO',
    telefone: '',
    celular: 73988072711,
    email: 'EZEQUIEL.MIZRAHI@GMAIL.COM',
    vt: '052VT/24-IS',
    data_vt: '02/20/2024',
    localidade: 'SANTA CRUZ CABRALIA',
    status: 'ARQUIVADA',
    protocolo: '23081/23',
    data: '2023'
  },
  {
    empreendimento: 'JARDINS DE TAPERAPUAN RESIDENCES 2',
    tipo: 'EMISSÃO',
    empresa: 'CONSTRUTORA INCORPORADA PINHEIRO VIANA LTDA',
    nomeInteressado: 'AGNO SOUZA',
    telefone: '',
    celular: 73991793141,
    email: 'CONSTRUTORAPINHEIROVIANA@OUTLOOK.COM',
    vt: '032VT/24-IS',
    data_vt: '01/26/2024',
    localidade: 'PORTO SEGURO',
    status: 'ARQUIVADA',
    protocolo: '22134/23',
    data: '2023'
  }
]
// alert('teste')

// async function carregarBD(param) {
//   try {
//     const docRef = await addDoc(collection(db, 'evtes'), param)
//     console.log('Documento escrito com ID: ', docRef.id)
//     return docRef.id
//   } catch (e) {
//     console.log(e)
//   }
// }

// function registrarDados() {
//   abastecer2023.map(item => {
//     carregarBD(item)
//   })
// }

// const JogarBD = document.getElementById('abastecerEvte')

// JogarBD.addEventListener('click', () => registrarDados())
